web:
  image: nginx:latest
  ports:
    - "8089:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  # image: php:7.2-fpm
  volumes: 
    - ./code:/code
  # environment:
  #   XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    # - maildev

mysql:
  image: mysql:latest
  ports:
    - "33306:3306"
  environment: 
    - MYSQL_DATABASE=db
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_HOST=localhost

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PMA_ARBITRARY=1
    # - PHP_UPLOAD_MAX_FILESIZE=100MB

# maildev:
#   image: djfarrelly/maildev
#   ports:
#    - "8081:80"